version: '3.8'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm run dev
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
